spring.application.name=studentmanager

# Port cho ng dung
server.port=8080

# Cau hinh H2 Database (database luu ra file)
spring.datasource.url=jdbc:h2:file:./data/studentdb   
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Tu ung tao schema tu entity
spring.jpa.hibernate.ddl-auto=update

# Hien thi SQL trong console
spring.jpa.show-sql=true

# Giao dien web cua H2 Console (de xem du lieu)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

